        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:05 2014
        MODULE FNCALCULATEPHASE__genmod
          INTERFACE 
            SUBROUTINE FNCALCULATEPHASE(PHASE,K)
              COMPLEX(KIND=8) :: PHASE
              REAL(KIND=8) :: K(2)
            END SUBROUTINE FNCALCULATEPHASE
          END INTERFACE 
        END MODULE FNCALCULATEPHASE__genmod
