        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:06 2014
        MODULE FNCLOSEFILES__genmod
          INTERFACE 
            SUBROUTINE FNCLOSEFILES
            END SUBROUTINE FNCLOSEFILES
          END INTERFACE 
        END MODULE FNCLOSEFILES__genmod
