        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:06 2014
        MODULE FNCNTPHONON__genmod
          INTERFACE 
            SUBROUTINE FNCNTPHONON
            END SUBROUTINE FNCNTPHONON
          END INTERFACE 
        END MODULE FNCNTPHONON__genmod
