        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:05 2014
        MODULE FNCNTELECTRON__genmod
          INTERFACE 
            SUBROUTINE FNCNTELECTRON
            END SUBROUTINE FNCNTELECTRON
          END INTERFACE 
        END MODULE FNCNTELECTRON__genmod
