        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:06 2014
        MODULE FNGEOMPROP__genmod
          INTERFACE 
            SUBROUTINE FNGEOMPROP
            END SUBROUTINE FNGEOMPROP
          END INTERFACE 
        END MODULE FNGEOMPROP__genmod
