        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:05 2014
        MODULE FNGRAPHENEPHONON__genmod
          INTERFACE 
            SUBROUTINE FNGRAPHENEPHONON(OMEGA,U_PH,K)
              REAL(KIND=8) :: OMEGA(6)
              COMPLEX(KIND=8) :: U_PH(6,6)
              REAL(KIND=8) :: K(2)
            END SUBROUTINE FNGRAPHENEPHONON
          END INTERFACE 
        END MODULE FNGRAPHENEPHONON__genmod
