        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:06 2014
        MODULE FNINPUT__genmod
          INTERFACE 
            SUBROUTINE FNINPUT
            END SUBROUTINE FNINPUT
          END INTERFACE 
        END MODULE FNINPUT__genmod
