        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:06 2014
        MODULE FNOPENFILES__genmod
          INTERFACE 
            SUBROUTINE FNOPENFILES
            END SUBROUTINE FNOPENFILES
          END INTERFACE 
        END MODULE FNOPENFILES__genmod
