        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:06 2014
        MODULE FNPHYSCONST__genmod
          INTERFACE 
            SUBROUTINE FNPHYSCONST
            END SUBROUTINE FNPHYSCONST
          END INTERFACE 
        END MODULE FNPHYSCONST__genmod
