        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 08 08:55:06 2014
        MODULE FNSCATTERING__genmod
          INTERFACE 
            SUBROUTINE FNSCATTERING
            END SUBROUTINE FNSCATTERING
          END INTERFACE 
        END MODULE FNSCATTERING__genmod
